### ISSUE TITLE
Deprecate old website

### ISSUE THREAD

**Issue by Divide-By-0** [DNSCrypt/dnscrypt-website#32]
Hello, https://www.dnscrypt.org/ is still live, and there is no banner or reference on that page that there has been any maintenance since 2017, nor a link to the new .info site. Due to the casino recommendation quotes, it looks like an untrustworthy project. It would be great to update these references and add redirects and banners on the old site for the new site, or delete it entirely.

**Comment by jedisct1** [comment]
Owner appears to be called ["James Awland"](https://www.bestcasino.co.uk/aboutme/) (probably a nickname).

A Google Search for that name returns pages added to hacked wordpress websites, in order to promote his casino business. Live example:

https://dauphine-taxi.fr/le-concessionnaire-online-blackjack-ios-obtient-ace-france-2023/

**Comment by Divide-By-0** [comment]
Can you maybe at least contact cloudflare and the rfc authors to change their backlinks? 

These all go to the wrong site:
https://blog.cloudflare.com/cloudflare-research-two-years-in
https://cs.wikipedia.org/wiki/Domain_Name_System_Security_Extensions
https://github.com/A3sal0n/FalconGate
https://rfc-annotations.research.icann.org/rfc7858.html

You should at least add some h1/h2 tags and fix your poor Google's Core Web Vitals score!

**Comment by jedisct1** [comment]
If you can help, please do!

**Comment by jedisct1** [comment]
Source of the website is here https://github.com/dnscrypt/dnscrypt-website
